# Generated by Django 4.2.7 on 2023-12-07 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_weight_kg'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gender',
            new_name='Gender2',
        ),
    ]
