# Generated by Django 4.2.7 on 2024-01-21 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conversation', '0002_remove_conversation_training_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationmessage',
            name='sent_to',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_messages2', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
