# Generated by Django 4.2.7 on 2023-12-13 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0007_gender_alter_user_gender_delete_gender2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('link_do_youtube', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseInPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reps_amount', models.PositiveIntegerField()),
                ('sets_amount', models.PositiveIntegerField()),
                ('pause', models.PositiveIntegerField()),
                ('tempo', models.CharField(max_length=7)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training_programs.exercise')),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='TypesOfExercises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingPlanInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_of_one_training_in_minutes', models.PositiveIntegerField(help_text='Czas treningu w minutach')),
                ('amount_of_days', models.PositiveIntegerField(help_text='Liczba dni')),
                ('goals', models.ManyToManyField(to='training_programs.goal')),
                ('prefer_exercises', models.ManyToManyField(to='training_programs.exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('amount_of_days', models.PositiveIntegerField()),
                ('trainer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.trainer')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField()),
                ('exercises', models.ManyToManyField(through='training_programs.ExerciseInPlan', to='training_programs.exercise')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training_programs.trainingplan')),
            ],
        ),
        migrations.AddField(
            model_name='exerciseinplan',
            name='training_day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training_programs.trainingday'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='types',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training_programs.typesofexercises'),
        ),
    ]
