# Generated by Django 4.2.7 on 2023-12-15 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_gender_alter_user_gender_delete_gender2'),
        ('training_programs', '0003_trainingplan_plan_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingplan',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.trainer'),
        ),
    ]
