# Generated by Django 4.2.7 on 2024-01-20 12:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('training_programs', '0006_alter_trainingplaninfo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingplan',
            name='plan_owner',
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='plan_owner',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
