# Generated by Django 4.2.7 on 2024-01-20 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('training_programs', '0007_remove_trainingplan_plan_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingplan',
            name='plan_owner',
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='plan_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
