# Generated by Django 4.2.7 on 2024-01-23 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('training_programs', '0008_remove_trainingplan_plan_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingplaninfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
